import React, { useEffect, useState } from 'react';
import './ReportsLayout.css';

const ReportsLayout = () => {
  const [reports, setReports] = useState([]);

  useEffect(() => {
    // Load user's medical reports/appointment history
    const allAppointments = JSON.parse(localStorage.getItem('allAppointments') || '[]');
    setReports(allAppointments);
  }, []);

  const handleViewReport = (report) => {
    // Display report details in an alert or modal
    alert(`Report Details:\n\nDoctor: ${report.doctorName}\nSpeciality: ${report.doctorSpeciality}\nDate: ${report.date}\nTime Slot: ${report.timeSlot}\nPatient: ${report.patientName}\nPhone: ${report.phoneNumber}`);
  };

  const handleDownloadReport = (report, index) => {
    // Create a text file with report details
    const reportContent = `MEDICAL REPORT\n\nSerial Number: ${index + 1}\nDoctor Name: ${report.doctorName}\nDoctor Speciality: ${report.doctorSpeciality}\nAppointment Date: ${report.date}\nTime Slot: ${report.timeSlot}\nPatient Name: ${report.patientName}\nPhone Number: ${report.phoneNumber}\n\nThis is a medical appointment report generated by StayHealthy.`;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Report_${report.doctorName.replace(/\s+/g, '_')}_${report.date}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="reports-layout-container">
      <h2>Reports</h2>
      
      {reports.length > 0 ? (
        <div className="reports-table-container">
          <table className="reports-table">
            <thead>
              <tr>
                <th>Serial Number</th>
                <th>Doctor Name</th>
                <th>Doctor Speciality</th>
                <th>View Report</th>
                <th>Download Report</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report, index) => (
                <tr key={report.id}>
                  <td>{index + 1}</td>
                  <td>{report.doctorName}</td>
                  <td>{report.doctorSpeciality}</td>
                  <td>
                    <button 
                      className="view-report-btn"
                      onClick={() => handleViewReport(report)}
                    >
                      View Report
                    </button>
                  </td>
                  <td>
                    <button 
                      className="download-report-btn"
                      onClick={() => handleDownloadReport(report, index)}
                    >
                      Download Report
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="no-reports">
          <p>No appointments found.</p>
          <p>Book an appointment to see your reports here.</p>
        </div>
      )}
    </div>
  );
};

export default ReportsLayout;
